# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - name: Build android app
        uses: oxr463/setup-cordova@0.0.2
        with:
          exec: |
            cd itemcounter && \
            cordova platform add android && \
            cordova build --no-telemetry --release && \
            (cd ./platforms/android && ./gradlew app:bundleRelease) && \
            cp "$(find . -name '*.aab')" ../
      - name: Sign app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ./
          signingKeyBase64: ${{ secrets.ANDROID_SIGN_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets. KEY_PASS }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotcounter
          path: ./*.aab
