# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - name: Build app
        uses: oxr463/setup-cordova@0.0.2
        with:
          exec: |
            cd itemcounter && \
            cordova platform add android && \
            cordova build --no-telemetry --release && \
            cp "$(find . -name '*.apk')" ../
      - name: Extract certificate
        env:
          AUTH: ${{ secrets.ANDROID_SIGN_KEY }}
        run: echo "$AUTH" | base64 --decode > ANDROID_SIGN_KEY && pwd && ls -l
      - name: Sign app
        uses: oxr463/setup-cordova@0.0.2
        with:
          exec: |
            jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ./ANDROID_SIGN_KEY ./*.apk dotcounter -storepass $KEY_PASS
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotcounter
          path: ./*.apk
